version: '3'
services:
  chatbot:
    build: .
    image: hkstpchatbot
    ports:
      - "22303:5000"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]
