version: '3'
services:
  chatbot:
    build: .
    image: hkstpchatbot
    ports:
      - "22303:5000"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    privileged: true
    command: ["/usr/local/etc/redis/redis.conf"]
