version: '3'
services:
  chatbot:
    build: .
    image: python:3.10
    environment:
      OPENAI_API_KEY: '${API_KEY}'
    ports:
      - "22303:8501"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"

