version: '3'
services:
  chatbot:
    build: .
    image: hkstpchatbot-dev
    environment:
      OPENAI_API_KEY: '${API_KEY}'
    ports:
      - "22303:5000"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack
    ports:
      - "9736:6379"
      - "8002:8001"
    expose: "9736"
