name: Deploy
on:
  push:
    branches:
      - dev

env:
  DEP_PATH: ./requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Server for Dev
        uses: AEnterprise/rsync-deploy@v1.0.2
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: -avz --exclude='config.ini'
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          FOLDER: "./"
          SERVER_IP: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION_DEV }}  #TODO build test env

      # - name: Restart Chatbot
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.DEPLOY_KEY }}
      #     port: ${{ secrets.SERVER_PORT }}

      #     script: |
      #       cd ${{ secrets.SERVER_DESTINATION_DEV }}
      #       sudo docker compose up


      #     # sudo docker compose up -d --force-recreate --no-deps chatbot